# Generated by Django 4.1.1 on 2022-09-25 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('svg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('publish_date', models.DateTimeField()),
                ('side_sketch', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='side_sketch', to='catalog.sketch')),
                ('top_sketch', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='top_sketch', to='catalog.sketch')),
            ],
        ),
    ]
