# Generated by Django 4.1.1 on 2022-09-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blueprint',
            new_name='Product',
        ),
    ]
