# Generated by Django 4.1.1 on 2022-09-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='heel_height',
            field=models.FloatField(default=0),
        ),
    ]
