# Generated by Django 4.1.2 on 2022-11-22 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(default='painting/default.svg', upload_to='painting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='sketch_xy',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='sketch_yz',
        ),
        migrations.AddField(
            model_name='shoe',
            name='sketch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sketch', to='catalog.sketch'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='painting',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='painting', to='catalog.painting'),
        ),
    ]
