# Generated by Django 4.1.2 on 2022-11-22 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_painting_remove_shoe_sketch_xy_remove_shoe_sketch_yz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(default='drawing/default.svg', upload_to='drawing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='sketch',
        ),
        migrations.DeleteModel(
            name='Sketch',
        ),
        migrations.AddField(
            model_name='shoe',
            name='line_art',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='line_art', to='catalog.drawing'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='painting',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='painting', to='catalog.drawing'),
        ),
        migrations.DeleteModel(
            name='Painting',
        ),
    ]
