# Generated by Django 4.1.1 on 2022-09-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_heel_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='glb',
            field=models.FileField(default='glb/default.glb', upload_to='glb'),
        ),
    ]
