# Generated by Django 4.1.2 on 2022-12-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_drawing_remove_shoe_sketch_delete_sketch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='line_art',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='painting',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Drawing',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
