# Generated by Django 4.1.1 on 2022-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_sketch_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view_x',
            field=models.FloatField(default=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_y',
            field=models.FloatField(default=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_z',
            field=models.FloatField(default=150),
        ),
    ]
