# Generated by Django 4.1.1 on 2022-09-30 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_view_x_alter_product_view_y_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='glb',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='sketch',
            old_name='publish_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heel_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_sketch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_sketch',
        ),
        migrations.RemoveField(
            model_name='sketch',
            name='svg',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sketch',
            name='file',
            field=models.FileField(default='svg/default.svg', upload_to='svg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_x',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_y',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_z',
            field=models.FloatField(default=100),
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
                ('heel_height', models.FloatField(default=0.5)),
                ('sketch_xy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sketch_xy', to='catalog.sketch')),
                ('sketch_yz', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sketch_yz', to='catalog.sketch')),
            ],
            options={
                'abstract': False,
            },
            bases=('catalog.product', models.Model),
        ),
    ]
