# Generated by Django 4.1.1 on 2022-09-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_glb_product_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(default='product/default.glb', upload_to='product'),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='file',
            field=models.FileField(default='sketch/default.svg', upload_to='sketch'),
        ),
    ]
