# Generated by Django 4.1.1 on 2023-04-20 14:50

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bool',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Float',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Int',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.IntegerField(default=0)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu', to='core.part')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu', to='core.tag')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.IntegerField(default=0)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps', to='core.part')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps', to='core.string')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.IntegerField(default=0)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp1', to='core.part')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp2', to='core.part')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.IntegerField(default=0)),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi', to='core.int')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi', to='core.part')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.IntegerField(default=0)),
                ('f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf', to='core.float')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf', to='core.part')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartBool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.IntegerField(default=0)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb', to='core.bool')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb', to='core.part')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='part',
            name='b',
            field=models.ManyToManyField(blank=True, related_name='r', through='core.PartBool', to='core.bool'),
        ),
        migrations.AddField(
            model_name='part',
            name='f',
            field=models.ManyToManyField(blank=True, related_name='r', through='core.PartFloat', to='core.float'),
        ),
        migrations.AddField(
            model_name='part',
            name='i',
            field=models.ManyToManyField(blank=True, related_name='r', through='core.PartInt', to='core.int'),
        ),
        migrations.AddField(
            model_name='part',
            name='p',
            field=models.ManyToManyField(blank=True, related_name='r', through='core.PartPart', to='core.part'),
        ),
        migrations.AddField(
            model_name='part',
            name='s',
            field=models.ManyToManyField(blank=True, related_name='r', through='core.PartString', to='core.string'),
        ),
        migrations.AddField(
            model_name='part',
            name='u',
            field=models.ManyToManyField(blank=True, related_name='r', through='core.PartUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
