# Generated by Django 4.1.1 on 2023-04-21 23:22

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bool',
            fields=[
                ('id', models.CharField(default=core.models.make_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Float',
            fields=[
                ('id', models.CharField(default=core.models.make_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Int',
            fields=[
                ('id', models.CharField(default=core.models.make_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.CharField(default=core.models.make_id, max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.CharField(default=core.models.make_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=core.models.make_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu', to='core.part')),
                ('pt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu', to='core.tag')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up', to=settings.AUTH_USER_MODEL)),
                ('ut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='up', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part_String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps', to='core.part')),
                ('pt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps', to='core.tag')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp', to='core.string')),
                ('st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part_Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp1', to='core.part')),
                ('p1t', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp1', to='core.tag')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp2', to='core.part')),
                ('p2t', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp2', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part_Int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip', to='core.int')),
                ('it', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip', to='core.tag')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi', to='core.part')),
                ('pt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part_Float',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp', to='core.float')),
                ('ft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fp', to='core.tag')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf', to='core.part')),
                ('pt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part_Bool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp', to='core.bool')),
                ('bt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bp', to='core.tag')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb', to='core.part')),
                ('pt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pb', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='part',
            name='b',
            field=models.ManyToManyField(blank=True, related_name='p', through='core.Part_Bool', to='core.bool'),
        ),
        migrations.AddField(
            model_name='part',
            name='f',
            field=models.ManyToManyField(blank=True, related_name='p', through='core.Part_Float', to='core.float'),
        ),
        migrations.AddField(
            model_name='part',
            name='i',
            field=models.ManyToManyField(blank=True, related_name='p', through='core.Part_Int', to='core.int'),
        ),
        migrations.AddField(
            model_name='part',
            name='p',
            field=models.ManyToManyField(blank=True, through='core.Part_Part', to='core.part'),
        ),
        migrations.AddField(
            model_name='part',
            name='s',
            field=models.ManyToManyField(blank=True, related_name='p', through='core.Part_String', to='core.string'),
        ),
        migrations.AddField(
            model_name='part',
            name='t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p', to='core.tag'),
        ),
        migrations.AddField(
            model_name='part',
            name='u',
            field=models.ManyToManyField(blank=True, related_name='p', through='core.Part_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
