# Generated by Django 4.1.2 on 2022-12-22 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(default='product/default.glb', upload_to='product')),
                ('camera_x', models.FloatField(default=0)),
                ('camera_y', models.FloatField(default=0)),
                ('camera_z', models.FloatField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.product')),
                ('heel_height', models.FloatField(default=0.5)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.product',),
        ),
    ]
