# Generated by Django 4.1.1 on 2023-01-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='camera_x',
        ),
        migrations.RemoveField(
            model_name='product',
            name='camera_y',
        ),
        migrations.RemoveField(
            model_name='product',
            name='camera_z',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
