# Generated by Django 4.1.1 on 2023-05-04 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.gdb_connect_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_bool',
            name='n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e', to='core.bool'),
        ),
        migrations.AlterField(
            model_name='part_bool',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_bool',
            name='t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='be', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e', to='core.float'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fe', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fe', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e', to='core.int'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ie', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ie', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_part',
            name='n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_part',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_part',
            name='t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pe', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e', to='core.string'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='se', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e', to=settings.gdb_connect_MODEL),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ue', to='core.tag'),
        ),
    ]
