# Generated by Django 4.1.1 on 2023-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='p',
            field=models.ManyToManyField(blank=True, related_name='r', through='core.Part_Part', to='core.part'),
        ),
    ]
