# Generated by Django 4.1.1 on 2023-12-21 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="user",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.RenameField(
            model_name="repo",
            old_name="description",
            new_name="story",
        ),
        migrations.RemoveField(
            model_name="repo",
            name="team",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
