# Generated by Django 4.1.1 on 2023-04-20 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartBool',
            new_name='Part_Bool',
        ),
        migrations.RenameModel(
            old_name='PartFloat',
            new_name='Part_Float',
        ),
        migrations.RenameModel(
            old_name='PartInt',
            new_name='Part_Int',
        ),
        migrations.RenameModel(
            old_name='PartPart',
            new_name='Part_Part',
        ),
        migrations.RenameModel(
            old_name='PartString',
            new_name='Part_String',
        ),
        migrations.RenameModel(
            old_name='PartUser',
            new_name='Part_User',
        ),
    ]
