# Generated by Django 5.0 on 2023-12-30 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commit",
            old_name="nodes",
            new_name="content",
        ),
    ]
