# Generated by Django 4.1.1 on 2023-04-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_partbool_part_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='t',
            field=models.ManyToManyField(blank=True, related_name='r', to='core.tag'),
        ),
    ]
