# Generated by Django 5.0 on 2024-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_code_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code_access",
            name="node",
            field=models.CharField(max_length=32),
        ),
    ]
