# Generated by Django 4.1.1 on 2023-12-21 01:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_account_user_delete_team_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Repo",
        ),
    ]
