# Generated by Django 4.1.1 on 2023-04-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_part_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part_bool',
            old_name='pt',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='part_bool',
            old_name='bt',
            new_name='t2',
        ),
        migrations.RenameField(
            model_name='part_float',
            old_name='pt',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='part_float',
            old_name='ft',
            new_name='t2',
        ),
        migrations.RenameField(
            model_name='part_int',
            old_name='pt',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='part_int',
            old_name='it',
            new_name='t2',
        ),
        migrations.RenameField(
            model_name='part_part',
            old_name='p1t',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='part_part',
            old_name='p2t',
            new_name='t2',
        ),
        migrations.RenameField(
            model_name='part_string',
            old_name='pt',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='part_string',
            old_name='st',
            new_name='t2',
        ),
        migrations.RenameField(
            model_name='part_user',
            old_name='pt',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='part_user',
            old_name='ut',
            new_name='t2',
        ),
    ]
