# Generated by Django 5.0 on 2023-12-30 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_nodes_commit_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commit",
            old_name="flex",
            new_name="metadata",
        ),
        migrations.RenameField(
            model_name="repo",
            old_name="flex",
            new_name="metadata",
        ),
    ]
