# Generated by Django 4.1.1 on 2023-12-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_delete_repo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "repo",
                    models.CharField(
                        default="", max_length=16, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=64)),
                ("story", models.TextField(blank=True, default="", max_length=512)),
            ],
        ),
    ]
