# Generated by Django 4.1.1 on 2023-05-04 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.gdb_connect_MODEL),
        ('core', '0003_rename_p_part_bool_r_rename_p_part_float_r_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='b',
            field=models.ManyToManyField(related_name='p', through='core.Part_Bool', to='core.bool'),
        ),
        migrations.AlterField(
            model_name='part',
            name='f',
            field=models.ManyToManyField(related_name='p', through='core.Part_Float', to='core.float'),
        ),
        migrations.AlterField(
            model_name='part',
            name='i',
            field=models.ManyToManyField(related_name='p', through='core.Part_Int', to='core.int'),
        ),
        migrations.AlterField(
            model_name='part',
            name='p',
            field=models.ManyToManyField(related_name='r', through='core.Part_Part', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='s',
            field=models.ManyToManyField(related_name='p', through='core.Part_String', to='core.string'),
        ),
        migrations.AlterField(
            model_name='part',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part',
            name='u',
            field=models.ManyToManyField(related_name='p', through='core.Part_User', to=settings.gdb_connect_MODEL),
        ),
        migrations.AlterField(
            model_name='part_bool',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fe', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ie', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_part',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue', to='core.tag'),
        ),
    ]
