# Generated by Django 5.0 on 2023-12-30 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_flex_commit_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commit",
            name="content",
        ),
    ]
