# Generated by Django 4.1.1 on 2023-04-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_part_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='t',
        ),
    ]
