# Generated by Django 4.1.1 on 2023-04-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_rename_pt_part_bool_t1_rename_bt_part_bool_t2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_bool',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb2', to='core.bool'),
        ),
        migrations.AlterField(
            model_name='part_bool',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb1', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_bool',
            name='t1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pb1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_bool',
            name='t2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pb2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf2', to='core.float'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf1', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='t1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='t2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi2', to='core.int'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi1', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='t1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='t2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps1', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps2', to='core.string'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='t1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='t2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu1', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='t1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='t2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu2', to=settings.AUTH_USER_MODEL),
        ),
    ]
