# Generated by Django 4.1.1 on 2023-12-21 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snap",
            fields=[
                (
                    "snap",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("node", models.CharField(max_length=16)),
                ("forw", models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name="repo",
            name="name",
        ),
        migrations.RemoveField(
            model_name="repo",
            name="story",
        ),
        migrations.AddField(
            model_name="repo",
            name="edit_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="flex",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repo",
            name="make_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="repo",
            name="repo",
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "commit",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("flex", models.JSONField()),
                ("make_time", models.DateTimeField(auto_now_add=True)),
                ("edit_time", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="contributions", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "committer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="core.repo",
                    ),
                ),
                (
                    "roots",
                    models.ManyToManyField(related_name="stems", to="core.commit"),
                ),
                (
                    "snaps",
                    models.ManyToManyField(related_name="commits", to="core.snap"),
                ),
            ],
        ),
    ]
