# Generated by Django 4.1.1 on 2023-05-04 16:35

from django.db import migrations


def make_test_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_part_b_alter_part_f_alter_part_i_alter_part_p_and_more'),
    ]

    operations = [
        migrations.RunPython(make_test_data),
    ]
