# Generated by Django 4.1.1 on 2023-04-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_part_bool_b_alter_part_bool_p_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part_bool',
            old_name='b',
            new_name='b2',
        ),
        migrations.RenameField(
            model_name='part_bool',
            old_name='p',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='part_float',
            old_name='f',
            new_name='f2',
        ),
        migrations.RenameField(
            model_name='part_float',
            old_name='p',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='part_int',
            old_name='i',
            new_name='i2',
        ),
        migrations.RenameField(
            model_name='part_int',
            old_name='p',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='part_string',
            old_name='p',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='part_string',
            old_name='s',
            new_name='s2',
        ),
        migrations.RenameField(
            model_name='part_user',
            old_name='p',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='part_user',
            old_name='u',
            new_name='u2',
        ),
    ]
