# Generated by Django 4.1.1 on 2023-04-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_part_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.IntegerField(default=0)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt', to='core.part')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt', to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='part',
            name='t',
            field=models.ManyToManyField(blank=True, related_name='r', through='core.Part_Tag', to='core.tag'),
        ),
    ]
