# Generated by Django 4.1.1 on 2023-03-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='owner',
        ),
    ]
