# Generated by Django 5.0 on 2023-12-22 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_snap_remove_repo_name_remove_repo_story_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="readers",
            field=models.ManyToManyField(
                related_name="readable_repos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="writers",
            field=models.ManyToManyField(
                related_name="writable_repos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
