# Generated by Django 5.0 on 2023-12-31 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_node_node_commit_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="commit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="core.commit",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="snap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="core.snap",
            ),
        ),
    ]
