# Generated by Django 4.1.1 on 2023-04-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_part_tag_part_t'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part_bool',
            old_name='o',
            new_name='n',
        ),
        migrations.RenameField(
            model_name='part_float',
            old_name='o',
            new_name='n',
        ),
        migrations.RenameField(
            model_name='part_int',
            old_name='o',
            new_name='n',
        ),
        migrations.RenameField(
            model_name='part_part',
            old_name='o',
            new_name='n',
        ),
        migrations.RenameField(
            model_name='part_string',
            old_name='o',
            new_name='n',
        ),
        migrations.RenameField(
            model_name='part_tag',
            old_name='o',
            new_name='n',
        ),
        migrations.RenameField(
            model_name='part_user',
            old_name='o',
            new_name='n',
        ),
    ]
