# Generated by Django 4.1.1 on 2023-04-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_b_part_bool_b2_rename_p_part_bool_p1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part_bool',
            old_name='p1',
            new_name='m1',
        ),
        migrations.RenameField(
            model_name='part_bool',
            old_name='b2',
            new_name='m2',
        ),
        migrations.RenameField(
            model_name='part_float',
            old_name='p1',
            new_name='m1',
        ),
        migrations.RenameField(
            model_name='part_float',
            old_name='f2',
            new_name='m2',
        ),
        migrations.RenameField(
            model_name='part_int',
            old_name='p1',
            new_name='m1',
        ),
        migrations.RenameField(
            model_name='part_int',
            old_name='i2',
            new_name='m2',
        ),
        migrations.RenameField(
            model_name='part_part',
            old_name='p1',
            new_name='m1',
        ),
        migrations.RenameField(
            model_name='part_part',
            old_name='p2',
            new_name='m2',
        ),
        migrations.RenameField(
            model_name='part_string',
            old_name='p1',
            new_name='m1',
        ),
        migrations.RenameField(
            model_name='part_string',
            old_name='s2',
            new_name='m2',
        ),
        migrations.RenameField(
            model_name='part_user',
            old_name='p1',
            new_name='m1',
        ),
        migrations.RenameField(
            model_name='part_user',
            old_name='u2',
            new_name='m2',
        ),
    ]
