# Generated by Django 4.1.1 on 2023-06-11 23:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part_bool',
            unique_together={('r', 'n', 't')},
        ),
        migrations.AlterUniqueTogether(
            name='part_float',
            unique_together={('r', 'n', 't')},
        ),
        migrations.AlterUniqueTogether(
            name='part_int',
            unique_together={('r', 'n', 't')},
        ),
        migrations.AlterUniqueTogether(
            name='part_part',
            unique_together={('r', 'n', 't')},
        ),
        migrations.AlterUniqueTogether(
            name='part_string',
            unique_together={('r', 'n', 't')},
        ),
        migrations.AlterUniqueTogether(
            name='part_user',
            unique_together={('r', 'n', 't')},
        ),
    ]
