# Generated by Django 4.1.1 on 2023-11-13 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.gdb_connect_MODEL),
        ("core", "0006_alter_part_bool_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package", models.CharField(default="", max_length=16)),
                ("name", models.CharField(default="", max_length=64)),
                ("description", models.TextField(default="", max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(default="", max_length=16)),
                ("name", models.CharField(default="", max_length=64)),
                ("description", models.TextField(default="", max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gdb_user", models.CharField(default="", max_length=16)),
                ("gdb_key", models.CharField(default="", max_length=16)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.gdb_connect_MODEL,
                    ),
                ),
            ],
        ),
    ]
