# Generated by Django 4.1.1 on 2023-04-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_p1_part_bool_m1_rename_b2_part_bool_m2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='t',
        ),
    ]
