# Generated by Django 5.0 on 2023-12-22 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_repo_readers_repo_writers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commit",
            old_name="commit",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="repo",
            old_name="repo",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="snap",
            old_name="snap",
            new_name="id",
        ),
    ]
