# Generated by Django 4.1.1 on 2023-11-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_package_team_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="description",
            field=models.TextField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, default="", max_length=512),
        ),
    ]
