# Generated by Django 4.1.1 on 2023-11-11 11:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="gdb_password",
            field=models.CharField(default=core.models.make_id, max_length=16),
        ),
        migrations.AlterField(
            model_name="account",
            name="gdb_username",
            field=models.CharField(default=core.models.make_id, max_length=16),
        ),
    ]
