# Generated by Django 4.1.1 on 2023-04-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_description_product_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('sketch', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.sketch')),
            ],
        ),
    ]
