# Generated by Django 4.1.1 on 2023-04-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_part_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='v',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
