# Generated by Django 5.0 on 2023-12-22 14:49

import core.api.util
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_commit_commit_id_rename_repo_repo_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commit",
            name="id",
            field=models.CharField(
                default=core.api.util.make_id,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="id",
            field=models.CharField(
                default=core.api.util.make_id,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="snap",
            name="id",
            field=models.CharField(
                default=core.api.util.make_id,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
