# Generated by Django 4.1.1 on 2023-04-13 13:07

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_rename_description_product_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Float_Atom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.TextField(default=core.models.random_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='story',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Part_Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.key')),
                ('part', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.part')),
                ('val', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='val', to='core.part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Float_Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.key')),
                ('part', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.part')),
                ('val', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.float_atom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
