# Generated by Django 4.1.1 on 2023-04-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_description_product_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('sketch', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.sketch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sketch',
            name='a',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='a', to='core.vector'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='b',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='core.vector'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.line'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='line',
            name='point',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.vector'),
        ),
        migrations.AddField(
            model_name='line',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
