# Generated by Django 4.1.1 on 2023-11-11 12:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_account_gdb_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.CharField(
                default=core.models.make_id,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
