# Generated by Django 4.1.1 on 2023-04-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_part_t_alter_tag_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='part_bool',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pb1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_bool',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pb2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_float',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_int',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_part',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_part',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_string',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps2', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu1', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part_user',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu2', to='core.tag'),
        ),
    ]
