# Generated by Django 5.0 on 2023-12-22 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_commit_id_alter_repo_id_alter_snap_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commit",
            name="readers",
            field=models.ManyToManyField(
                related_name="readable_commits", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="commit",
            name="writers",
            field=models.ManyToManyField(
                related_name="writable_commits", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
