# Generated by Django 4.1.1 on 2023-04-13 13:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_float_atom_key_part_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='val',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
