# Generated by Django 4.1.1 on 2023-04-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_id_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='deps',
            field=models.ManyToManyField(blank=True, related_name='sups', to='core.part'),
        ),
    ]
