# Generated by Django 4.1.1 on 2023-11-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_package_description_alter_team_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="gdb_key",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="account",
            name="gdb_user",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="package",
            name="package",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="team",
            name="team",
            field=models.CharField(default="", max_length=64),
        ),
    ]
