# Generated by Django 4.1.1 on 2023-04-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_part_deps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='char',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='float',
            name='parts',
        ),
        migrations.AddField(
            model_name='part',
            name='chars',
            field=models.ManyToManyField(related_name='parts', to='core.char'),
        ),
        migrations.AddField(
            model_name='part',
            name='floats',
            field=models.ManyToManyField(related_name='parts', to='core.float'),
        ),
    ]
