# Generated by Django 4.1.1 on 2023-11-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_account_gdb_key_alter_account_gdb_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="team",
            field=models.CharField(default="", max_length=64),
        ),
    ]
