# Generated by Django 4.1.1 on 2023-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_key_val_alter_product_id_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Char_Atom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=64)),
            ],
        ),
    ]
