# Generated by Django 4.1.1 on 2023-04-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_char_atom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='float_prop',
            name='key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.char_atom'),
        ),
        migrations.AlterField(
            model_name='part_prop',
            name='key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.char_atom'),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
