# Generated by Django 4.1.1 on 2023-04-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='chars',
            field=models.ManyToManyField(blank=True, related_name='parts', to='core.char'),
        ),
        migrations.AlterField(
            model_name='part',
            name='floats',
            field=models.ManyToManyField(blank=True, related_name='parts', to='core.float'),
        ),
    ]
