# Generated by Django 4.1.1 on 2023-04-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_part_chars_alter_part_floats'),
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RenameField(
            model_name='float',
            old_name='val',
            new_name='v',
        ),
        migrations.RemoveField(
            model_name='part',
            name='chars',
        ),
        migrations.RemoveField(
            model_name='part',
            name='deps',
        ),
        migrations.RemoveField(
            model_name='part',
            name='floats',
        ),
        migrations.AddField(
            model_name='part',
            name='f',
            field=models.ManyToManyField(blank=True, related_name='u', to='core.float'),
        ),
        migrations.AddField(
            model_name='part',
            name='p',
            field=models.ManyToManyField(blank=True, related_name='u', to='core.part'),
        ),
        migrations.DeleteModel(
            name='Char',
        ),
        migrations.AddField(
            model_name='part',
            name='s',
            field=models.ManyToManyField(blank=True, related_name='u', to='core.string'),
        ),
    ]
