# Generated by Django 4.1.1 on 2023-04-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_char_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='char_prop',
            name='val',
        ),
        migrations.RemoveField(
            model_name='float_prop',
            name='val',
        ),
        migrations.AddField(
            model_name='char_prop',
            name='atom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='atom', to='core.char_atom'),
        ),
        migrations.AddField(
            model_name='float_prop',
            name='atom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atom', to='core.float_atom'),
        ),
    ]
