# Generated by Django 4.1.1 on 2023-04-18 11:00

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_remove_product_date_product_date_edit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bool',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Int',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=64)),
                ('date_new', models.DateTimeField(auto_now_add=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(default='project/default.glb', upload_to='project')),
                ('public', models.BooleanField(default=False)),
                ('story', models.TextField(default='')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parts', models.ManyToManyField(blank=True, related_name='projects', to='core.part')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='part',
            name='b',
            field=models.ManyToManyField(blank=True, related_name='u', to='core.bool'),
        ),
        migrations.AddField(
            model_name='part',
            name='i',
            field=models.ManyToManyField(blank=True, related_name='u', to='core.int'),
        ),
    ]
