# Generated by Django 4.1.1 on 2023-04-18 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_bool_int_project_delete_product_part_b_part_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='p',
        ),
        migrations.AddField(
            model_name='part',
            name='c',
            field=models.ManyToManyField(blank=True, related_name='p', to='core.part'),
        ),
        migrations.AddField(
            model_name='part',
            name='u',
            field=models.ManyToManyField(blank=True, related_name='p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='part',
            name='b',
            field=models.ManyToManyField(blank=True, related_name='p', to='core.bool'),
        ),
        migrations.AlterField(
            model_name='part',
            name='f',
            field=models.ManyToManyField(blank=True, related_name='p', to='core.float'),
        ),
        migrations.AlterField(
            model_name='part',
            name='i',
            field=models.ManyToManyField(blank=True, related_name='p', to='core.int'),
        ),
        migrations.AlterField(
            model_name='part',
            name='s',
            field=models.ManyToManyField(blank=True, related_name='p', to='core.string'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
