# Generated by Django 4.1.1 on 2023-04-19 12:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_part_p_part_c_part_u_alter_part_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=core.models.random_id, max_length=16, primary_key=True, serialize=False)),
                ('v', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='part',
            name='t',
            field=models.ManyToManyField(blank=True, related_name='p', to='core.tag'),
        ),
    ]
