# Generated by Django 4.1.1 on 2023-04-19 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_tag_part_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='c',
        ),
        migrations.AddField(
            model_name='part',
            name='p',
            field=models.ManyToManyField(blank=True, related_name='r', to='core.part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='b',
            field=models.ManyToManyField(blank=True, related_name='r', to='core.bool'),
        ),
        migrations.AlterField(
            model_name='part',
            name='f',
            field=models.ManyToManyField(blank=True, related_name='r', to='core.float'),
        ),
        migrations.AlterField(
            model_name='part',
            name='i',
            field=models.ManyToManyField(blank=True, related_name='r', to='core.int'),
        ),
        migrations.AlterField(
            model_name='part',
            name='s',
            field=models.ManyToManyField(blank=True, related_name='r', to='core.string'),
        ),
        migrations.AlterField(
            model_name='part',
            name='t',
            field=models.ManyToManyField(blank=True, related_name='r', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='part',
            name='u',
            field=models.ManyToManyField(blank=True, related_name='r', to=settings.AUTH_USER_MODEL),
        ),
    ]
