"""
Django settings for delimit project.
Generated by 'django-admin startproject' using Django 4.1.1.
For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['delimit.art','www.delimit.art', 'graph.delimit', 'graph.delimit.art'] 

ROOT_URLCONF = 'delimit.urls'
ROOT_HOSTCONF = 'delimit.hosts'
DEFAULT_HOST= 'www'
PARENT_HOST = 'delimit.art'
SILKY_AUTHENTICATION = True
SILKY_AUTHORISATION = True

# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'graph.apps.GraphConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'django_hosts',
    'silk',
]

MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'silk.middleware.SilkyMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'delimit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
   'default': {
       'ENGINE':   'django.db.backends.postgresql_psycopg2',
       'NAME':     'delimit',
       'USER':     'delimit',
       'PASSWORD':  config('DB_PASSWORD'), 
       'HOST':     'localhost',
       'PORT': '',
   }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Django looks for additional static files to collect from here:
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'common/'), 
    config('AXIOM_LOCATION'),
)

#>>>>>>>>>>> https://djangodeployment.readthedocs.io/en/latest/05-static-files.html <<<<<<<<<<<<<<

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/') # dev  ##### STATIC_ROOT not used at all in dev

# Media files (user uploaded images, generated 3D models, etc)
# https://docs.djangoproject.com/en/4.1/topics/files/
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')   

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




#'corsheaders.middleware.CorsMiddleware',
#CORS_ALLOW_ALL_ORIGINS = True

#'csp.middleware.CSPMiddleware', 
# Content Security Policy
# CSP_IMG_SRC = ("'self'")
# CSP_STYLE_SRC = ("'self'")
# CSP_SCRIPT_SRC = ("'self'", 'https://graph.delimit.art')
# #CSP_STYLE_SRC = ("'unsafe-inline'", "https:")