# Generated by Django 4.1.1 on 2022-09-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
